name: Build Photo-CIE APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Scarica progetto
        uses: actions/checkout@v4

      - name: Installa Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Controlla progetto
        run: |
          echo "=== FILE PRINCIPALI ==="
          ls -la

          echo "=== CERCA FILE GRADLE ==="
          find . -name "gradlew" -o -name "build.gradle" -o -name "settings.gradle"

      - name: Permessi Gradle
        run: |
          chmod +x gradlew

      - name: Compila APK Debug
        run: |
          ./gradlew clean
          ./gradlew :app:assembleDebug --stacktrace --info

      - name: Cerca APK generato
        run: |
          echo "=== CERCO APK ==="
          find . -name "*.apk"

      - name: Carica APK
        uses: actions/upload-artifact@v4
        with:
          name: Photo-CIE-debug-apk
          path: |
            **/*.apk
