name: Build Photo-CIE APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Controllo progetto
        run: |
          ls -la
          find . -maxdepth 3 -name "build.gradle" -o -name "settings.gradle" -o -name "gradlew"

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Trova APK
        run: |
          find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Photo-CIE-debug
          path: "**/*.apk"
